spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/batch?serverTimeZone=Asia/Seoul
    username: root
    password: 1111
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      isolation-level-for-create: default

logging:
  level:
    root: info
    com.psc.sample : debug